### ISSUE TITLE
Contact context is missing

### ISSUE THREAD

**Issue by hsolbrig** [fhircat/jsonld_context_files#4]
[contextFiles/patient.context.jsonld]() has the following:
```
 "contact": {
      "@id": "fhir:Patient.contact",
      "@context": "patient.contact.context.jsonld"
    },
```
But there is no [contextFiles/patient.contact.context.jsonld]() on the server?

**Comment by cendle** [comment]
This has been fixed.  BackboneElements and Elements are now being processed and the appropriate context files are being created.
